version: '3.8'

services:
  web:
    # depends_on:
    #   - db
    build: .
    env_file:
      - .env
    ports:
      - "8081:8081"
    volumes:
      - .:/app
#   db:
#     image: postgres:alpine
#     environment:
#       - POSTGRES_USER=${DB_USER}
#       - POSTGRES_PASSWORD=${DB_PASSWORD}
#       - POSTGRES_DB=${DB_NAME}
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres-db:/var/lib/postgresql/data

#   migrate:
#     container_name: migrater
#     image: migrate/migrate

#     volumes:
#       - C:\Users\79170\gopets\bankappAutotest\migrations:/database
#     command: [ "-path", "/database", "-database", "postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable", "up" ]

  

# volumes:
#   postgres-db:
